export default [
  {
    id: 1,
    date: 'Feb 2019 – Jul 2020',
    title: 'Web Developer',
    company: 'Self-Taught',
    duration: '1 yr 6 mos',
    location: 'India',
    as: 'Self-employed',
    desc: 'freelancing projects clients  from LinkedIn',
  },
  {
    id: 2,
    date: 'Jul 2019 – Jul 2020',
    title: 'Web Developer',
    company: 'AttainU',
    duration: '1 yr 1 mo',
    location: 'Chennai, Tamil Nadu, India',
    as: 'Trainee',
    desc: `Worked as remote React developer building projects toy projects for learning includes many clones
    Tech Stack Used - React, Redux, Node, MongoDB, Vue, VUEX`,
  },
  {
    id: 3,
    date: 'Jul 2020 – Aug 2020',
    title: 'Frontend Developer',
    company: '9to5',
    duration: '2 mos',
    location: 'Noida, Uttar Pradesh, India',
    as: 'Internship',
    desc: `Handled UI part of websites using React/Redux and integrating the api.`,
  },
  {
    id: 4,
    date: 'Sep 2020 – Oct 2020',
    title: 'Frontend Developer',
    company: 'Solytics Partners Pvt. Ltd',
    duration: '2 mos',
    location: 'Pune, Maharashtra, India',
    as: 'Part-time',
    desc: `Contributing towards building quality, scalable front end applications using React, TypeScript. Managed a Team of 5 Internes.`,
  },
  {
    id: 5,
    date: 'Sep 2020 – Nov 2020',
    title: 'Frontend Developer',
    company: 'Les Transformations Learning Pvt. Ltd.',
    duration: '3 mos',
    location: 'Gurugram, Haryana, India',
    as: 'Full-time',
    desc: `Responsible for building Single page applications and websites using React/Redux and in Vue`,
  },
  {
    id: 6,
    date: 'Dec 2020 – Present',
    title: 'Software Engineer',
    company: 'Codalyze Technologies',
    duration: '1 mo',
    location: 'Mumbai, Maharashtra, India',
    as: 'Full-time',
    desc: ``,
  },
];
